In [1]:
import xarray as xr
import pandas as pd
import numpy as np
import json
from datetime import datetime, date, time, timedelta
import time as tm

In [160]:
def timestamp_to_datetime(df, col, unit='ms'):
    df[col] = pd.to_datetime(df[col], unit=unit, utc=True).map(lambda x: x.tz_convert("America/new_York"))
    return df

def drop(df):
    df = df.drop(columns=[
        'assetMainType',
        'quoteType',
        'realtime',
        'symbol',
        'reference.fsiDesc',
        'reference.description',
        'reference.otcMarketTier',
        'reference.exchangeName',
        'reference.isShortable',
        'fundamental.fundLeverageFactor',
        'quote.lastMICId',
        'quote.bidMICId',
        'quote.askMICId',
        #
        # 'ssid',
        # 'extended.askPrice',
        # 'extended.askSize',
        # 'extended.bidPrice',
        # 'extended.bidSize',
        # 'extended.lastPrice',
        # 'extended.lastSize',
        # 'extended.mark',
        # 'extended.quoteTime',
        # 'extended.totalVolume',
        # 'extended.tradeTime',
    ])
    return df

def time_convert(df):
    timestamp_to_datetime(df,'regular.regularMarketTradeTime')
    #timestamp_to_datetime(df,'extended.quoteTime')
    #timestamp_to_datetime(df,'extended.tradeTime')
    timestamp_to_datetime(df,'quote.askTime')
    timestamp_to_datetime(df,'quote.bidTime')
    timestamp_to_datetime(df,'quote.quoteTime')
    timestamp_to_datetime(df,'quote.tradeTime')
    return df

def process(df):
    df = time_convert(df)
    df = drop(df)
    df = df.set_index('ident')
    return df

In [161]:
df1 = process(pd.read_parquet('~/W_Projects/Quant_Trading/live_data/u00_2025-08-15_16:40.parquet'))
df2 = process(pd.read_parquet('~/W_Projects/Quant_Trading/live_data/u00_2025-08-15_19:40.parquet'))
df3 = process(pd.read_parquet('~/W_Projects/Quant_Trading/live_data/u00_2025-08-16_03:40.parquet'))
df4 = process(pd.read_parquet('~/W_Projects/Quant_Trading/live_data/u00_2025-08-16_11:40.parquet'))
df5 = process(pd.read_parquet('~/W_Projects/Quant_Trading/live_data/u00_2025-08-16_13:40.parquet'))

In [166]:
pd.set_option('display.max_rows', None)  # For Series
i = 2
pd.concat([
        df1.iloc[[i]],
        df2.iloc[[i]], 
        df3.iloc[[i]],
        df4.iloc[[i]],
        df5.iloc[[i]]
    ]).T

ident,UNH,UNH,UNH,UNH,UNH
assetSubType,COE,COE,COE,COE,COE
ssid,396502914.0,396502914.0,396502914.0,396502914.0,396502914.0
extended.askPrice,0.0,0.0,0.0,0.0,0.0
extended.askSize,0.0,0.0,0.0,0.0,0.0
extended.bidPrice,0.0,0.0,0.0,0.0,0.0
extended.bidSize,0.0,0.0,0.0,0.0,0.0
extended.lastPrice,304.97,304.97,304.97,304.97,304.97
extended.lastSize,58.0,58.0,58.0,58.0,58.0
extended.mark,0.0,0.0,0.0,0.0,0.0
extended.quoteTime,1755244800000.0,1755244800000.0,1755244800000.0,1755244800000.0,1755244800000.0
extended.totalVolume,0.0,0.0,0.0,0.0,0.0
extended.tradeTime,1755244798000.0,1755244798000.0,1755244798000.0,1755244798000.0,1755244798000.0
fundamental.avg10DaysVolume,18878940.0,18878940.0,18878940.0,18419363.0,18419363.0
fundamental.avg1YearVolume,9021334.0,9021334.0,9021334.0,9258861.0,9258861.0
fundamental.declarationDate,2025-08-13T00:00:00Z,2025-08-13T00:00:00Z,2025-08-13T00:00:00Z,2025-08-13T00:00:00Z,2025-08-13T00:00:00Z
fundamental.divAmount,8.84,8.84,8.84,8.84,8.84
fundamental.divExDate,2025-09-15T00:00:00Z,2025-09-15T00:00:00Z,2025-09-15T00:00:00Z,2025-09-15T00:00:00Z,2025-09-15T00:00:00Z
fundamental.divFreq,4.0,4.0,4.0,4.0,4.0
fundamental.divPayAmount,2.21,2.21,2.21,2.21,2.21
fundamental.divPayDate,2025-09-23T00:00:00Z,2025-09-23T00:00:00Z,2025-09-23T00:00:00Z,2025-09-23T00:00:00Z,2025-09-23T00:00:00Z
fundamental.divYield,3.25227,3.25227,3.25227,3.25611,3.25611
fundamental.eps,15.51,15.51,15.51,15.51,15.51
fundamental.lastEarningsDate,2025-07-29T00:00:00Z,2025-07-29T00:00:00Z,2025-07-29T00:00:00Z,2025-07-29T00:00:00Z,2025-07-29T00:00:00Z
fundamental.nextDivExDate,2025-12-15T00:00:00Z,2025-12-15T00:00:00Z,2025-12-15T00:00:00Z,2025-12-15T00:00:00Z,2025-12-15T00:00:00Z
fundamental.nextDivPayDate,2025-12-23T00:00:00Z,2025-12-23T00:00:00Z,2025-12-23T00:00:00Z,2025-12-23T00:00:00Z,2025-12-23T00:00:00Z
fundamental.peRatio,11.74503,11.74503,11.74503,13.1519,13.1519
quote.52WeekHigh,630.73,630.73,630.73,630.73,630.73
quote.52WeekLow,234.6,234.6,234.6,234.6,234.6
quote.askPrice,304.14,306.29,305.5,305.5,305.5
quote.askSize,10.0,2.0,2.0,2.0,2.0
quote.askTime,2025-08-15 16:39:41.032000-04:00,2025-08-15 19:39:06.301000-04:00,2025-08-15 19:59:59.636000-04:00,2025-08-15 19:59:59.636000-04:00,2025-08-15 19:59:59.636000-04:00
quote.bidPrice,304.1,306.04,304.79,304.79,304.79
quote.bidSize,2.0,1.0,1.0,1.0,1.0
quote.bidTime,2025-08-15 16:39:07.922000-04:00,2025-08-15 19:39:55.986000-04:00,2025-08-15 20:00:00.239000-04:00,2025-08-15 20:00:00.239000-04:00,2025-08-15 20:00:00.239000-04:00
quote.closePrice,271.49,271.49,271.49,271.49,271.49
quote.highPrice,310.3,310.3,310.3,310.3,310.3
quote.lastPrice,304.11,306.29,305.42,305.42,305.42
quote.lastSize,1.0,30.0,62.0,62.0,62.0
quote.lowPrice,294.71,294.71,294.71,294.71,294.71
quote.mark,304.1,306.04,304.01,304.01,304.01
quote.markChange,32.61,34.55,32.52,32.52,32.52
quote.markPercentChange,12.011492,12.726067,11.978342,11.978342,11.978342
quote.netChange,32.62,34.8,33.93,33.93,33.93
quote.netPercentChange,12.015176,12.818152,12.497698,12.497698,12.497698
quote.openPrice,301.71,301.71,301.71,301.71,301.71
quote.postMarketChange,0.1,2.28,1.41,1.41,1.41
quote.postMarketPercentChange,0.032894,0.749975,0.463801,0.463801,0.463801
quote.quoteTime,2025-08-15 16:39:41.032000-04:00,2025-08-15 19:39:55.986000-04:00,2025-08-15 20:00:00.239000-04:00,2025-08-15 20:00:00.239000-04:00,2025-08-15 20:00:00.239000-04:00
quote.securityStatus,Normal,Normal,Normal,Normal,Normal
quote.totalVolume,67436452.0,68137681.0,68198475.0,68198475.0,68198475.0
quote.tradeTime,2025-08-15 16:40:00.393000-04:00,2025-08-15 19:39:55.975000-04:00,2025-08-15 19:59:59.998000-04:00,2025-08-15 19:59:59.998000-04:00,2025-08-15 19:59:59.998000-04:00
reference.cusip,91324P102,91324P102,91324P102,91324P102,91324P102
reference.exchange,N,N,N,N,N
reference.isHardToBorrow,False,False,False,False,False
reference.htbQuantity,2309225.0,2309225.0,NaN,NaN,NaN
reference.htbRate,0.0,0.0,0.0,0.0,0.0
regular.regularMarketLastPrice,304.01,304.01,304.01,304.01,304.01
regular.regularMarketLastSize,1119730.0,1119730.0,1119730.0,1119730.0,1119730.0
regular.regularMarketNetChange,32.52,32.52,32.52,32.52,32.52
regular.regularMarketPercentChange,11.978342,11.978342,11.978342,11.978342,11.978342
regular.regularMarketTradeTime,2025-08-15 16:10:00-04:00,2025-08-15 19:00:00.001000-04:00,2025-08-15 19:00:00.001000-04:00,2025-08-15 19:00:00.001000-04:00,2025-08-15 19:00:00.001000-04:00
reference.fsiCode,None,None,None,None,None
invalidSymbols,None,None,None,None,None

In [158]:
pd.set_option('display.max_rows', 50)  # For Series
df5.sort_values('quote.tradeTime')

,ident,assetSubType,ssid,extended.askPrice,extended.askSize,extended.bidPrice,extended.bidSize,extended.lastPrice,extended.lastSize,extended.mark,extended.quoteTime,extended.totalVolume,extended.tradeTime,fundamental.avg10DaysVolume,fundamental.avg1YearVolume,fundamental.declarationDate,fundamental.divAmount,fundamental.divExDate,fundamental.divFreq,fundamental.divPayAmount,fundamental.divPayDate,fundamental.divYield,fundamental.eps,fundamental.lastEarningsDate,fundamental.nextDivExDate,fundamental.nextDivPayDate,fundamental.peRatio,quote.52WeekHigh,quote.52WeekLow,quote.askPrice,quote.askSize,quote.askTime,quote.bidPrice,quote.bidSize,quote.bidTime,quote.closePrice,quote.highPrice,quote.lastPrice,quote.lastSize,quote.lowPrice,quote.mark,quote.markChange,quote.markPercentChange,quote.netChange,quote.netPercentChange,quote.openPrice,quote.postMarketChange,quote.postMarketPercentChange,quote.quoteTime,quote.securityStatus,quote.totalVolume,quote.tradeTime,reference.cusip,reference.exchange,reference.isHardToBorrow,reference.htbRate,regular.regularMarketLastPrice,regular.regularMarketLastSize,regular.regularMarketNetChange,regular.regularMarketPercentChange,regular.regularMarketTradeTime,reference.fsiCode,invalidSymbols
4792,GJR,PRF,1.287285e+09,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,2025-08-08T00:00:00Z,1.28238,2025-08-14T00:00:00Z,12.0,0.10687,2025-08-15T00:00:00Z,5.16880,0.00000,None,2025-09-15T00:00:00Z,2025-09-15T00:00:00Z,0.00000,25.9500,24.46,27.68,1.0,2025-08-15 16:00:00.461000-04:00,22.6300,0.0,2025-08-15 16:00:03.289000-04:00,24.703135,0.0,24.810,0.0,0.0,24.810,0.106865,0.432597,0.106865,0.432597,0.0,0.00,0.00000,2025-08-15 16:00:03.289000-04:00,Normal,1.0,2025-08-04 14:34:58.985000-04:00,863121208,N,True,-14.00,24.810,0.0,0.0,0.0,2025-08-04 19:00:00.004000-04:00,None,None
5083,OFSSH,PRF,7.660233e+07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,None,1.23750,2025-07-15T00:00:00Z,4.0,0.30938,2025-07-31T00:00:00Z,5.29979,0.00000,2025-07-31T00:00:00Z,2025-10-15T00:00:00Z,2025-10-31T00:00:00Z,0.00000,23.4200,21.65,2147.48,0.0,2025-08-15 16:02:00-04:00,23.1100,1.0,2025-08-15 16:02:00-04:00,23.140000,0.0,23.350,0.0,0.0,23.350,0.210000,0.907519,0.210000,0.907519,0.0,0.00,0.00000,2025-08-15 16:00:01.803000-04:00,Closed,0.0,2025-08-05 13:12:31.457000-04:00,67103B704,Q,True,-14.25,23.350,0.0,0.0,0.0,2025-08-05 13:12:31.457000-04:00,None,None
4777,JBK,PRF,1.850771e+09,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.0,2024-12-23T00:00:00Z,1.58600,2025-02-14T00:00:00Z,2.0,0.79300,2025-02-18T00:00:00Z,6.04766,0.00000,None,2025-08-14T00:00:00Z,2025-08-18T00:00:00Z,0.00000,28.2000,24.72,29.31,2.0,2025-08-15 16:00:00.135000-04:00,0.0001,0.0,2025-08-15 16:00:03.771000-04:00,25.431875,0.0,26.225,0.0,0.0,26.225,0.793125,3.118626,0.793125,3.118626,0.0,0.00,0.00000,2025-08-15 16:00:03.771000-04:00,Normal,38.0,2025-08-07 10:42:55.964000-04:00,21988K859,N,True,-31.25,26.225,0.0,0.0,0.0,2025-08-07 19:00:00.002000-04:00,None,None
5090,HSPT,COE,1.042242e+08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.755245e+12,0.0,0.0,11776.0,53613.0,None,0.00000,None,0.0,0.00000,None,0.00000,0.00000,2025-05-16T00:00:00Z,None,None,73.47055,10.4400,10.01,16.44,2.0,2025-08-15 17:11:52.036000-04:00,10.2800,20.0,2025-08-15 16:26:16.857000-04:00,10.270000,0.0,10.270,0.0,0.0,10.270,0.000000,0.000000,0.000000,0.000000,0.0,0.00,0.00000,2025-08-15 17:11:52.036000-04:00,Closed,0.0,2025-08-07 13:34:33.933000-04:00,G4627B103,Q,None,NaN,10.270,0.0,0.0,0.0,2025-08-07 13:34:33.933000-04:00,None,None
4683,WHLRL,PRF,7.393356e+07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,0.0,417.0,805.0,None,1.75000,None,0.0,0.00000,None,1.22807,-1644.46819,2025-08-05T00:00:00Z,None,None,-5.69186,194.6501,65.00,2147.48,0.0,2025-08-15 16:04:00.304000-04:00,0.0100,97.0,2025-08-15 16:04:00.304000-04:00,146.780000,0.0,137.290,0.0,0.0,142.500,-4.280000,-2.915929,-9.490000,-6.465459,0.0,-5.21,-3.65614,2025-08-15 16:04:00.304000-04:00,Closed,9.0,2025-08-07 16:00:00.044000-04:00,963025804,Q,True,-11.25,142.500,0.0,0.0,0.0,2025-08-05 15:51:19.161000-04:00,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3400,errors,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,None,NaN,NaN,None,NaN,NaN,None,None,None,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,None,NaN,NaT,None,None,None,NaN,NaN,NaN,NaN,NaN,NaT,None,"[WFC/PA, BAC/PO, BAC/PN, COF/PI, FLG/PA, T/PA,..."
3835,errors,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,None,NaN,NaN,None,NaN,NaN,None,None,None,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,None,NaN,NaT,None,None,None,NaN,NaN,NaN,NaN,NaN,NaT,None,"[CODI/PB, USB/PA, RITM/PD, PSA/PP, VOYA/PB, GS..."
4275,errors,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,None,NaN,NaN,None,NaN,NaN,None,None,None,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,None,NaN,NaT,None,None,None,NaN,NaN,NaN,NaN,NaN,NaT,None,"[RIV/PA, PSA/PH, SCE/PN, KEY/PK, SNV/PE, IVR/P..."
4689,errors,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,None,NaN,NaN,None,NaN,NaN,None,None,None,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,None,NaN,NaT,None,None,None,NaN,NaN,NaN,NaN,NaN,NaT,None,"[PSA/PS, GS/PC, ICR/PA, AMH/PH, TWO/PB, DLR/PJ..."
5108,errors,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,None,NaN,NaN,None,NaN,NaN,None,None,None,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,None,NaN,NaT,None,None,None,NaN,NaN,NaN,NaN,NaN,NaT,None,"[AHT/PH, CHMI/PA, PRIF/PL, CDR/PC, WBS/PG, AUB..."

In [142]:
df2.to_parquet("jtest_00_out_01.parquet",index=False)

In [147]:
df2[['quote.tradeTime','ident']].to_parquet("jtest_00_out_01.parquet",index=False)